fix: migrate Analyzer to pre-push

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -4,3 +4,12 @@ then
   echo "un-commited changes found, do commit or stash them"
   exit 1
 fi
+
+echo "Run Analyzer..."
+flutter analyze
+
+if [ $? -ne 0 ] 
+then
+echo "flutter analyze error"
+  exit 1
+fi
